import React,{useState} from "react";
import { HistorysInterface } from "../models/IHistory";
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Container from '@mui/material/Container';
import Paper from '@mui/material/Paper';
import TextField from '@mui/material/TextField';
import Autocomplete from '@mui/material/Autocomplete';
import Grid from '@mui/material/Grid';
import { styled } from '@mui/material/styles';
import MenuItem from "@mui/material/MenuItem";
